version: '2'
services:
  cracker:
    image: cracker
    ports:
     - "5030:5030"
    depends_on:
      - shop
  shop:
    image: shop
    ports:
     - "8081:8081"
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - shop
    command: shop:8081
